### ISSUE TITLE
Fritzing files?

### ISSUE THREAD

**Issue by Ricardosgeral** [sparkfun/Logic_Level_Bidirectional#2]
Anyone have this in Fritzing?

**Comment by bboyho** [comment]
Hi,

It should be in our Fritzing repository located here => https://github.com/sparkfun/Fritzing_Parts/blob/master/products/12009_sfe_bi_directional_logic_level_converter.fzpz .

**Comment by loricrotser** [comment]
Just uploaded the fritzing part for this. Thank you for your patience!
[https://github.com/sparkfun/Fritzing_Parts/blob/master/products/12009_sfe_bi_directional_logic_level_converter.fzpz](https://github.com/sparkfun/Fritzing_Parts/blob/master/products/12009_sfe_bi_directional_logic_level_converter.fzpz)

**Comment by Ricardosgeral** [comment]
Thanks
