### ISSUE TITLE
3.3V output instead of 5V

### ISSUE THREAD

**Issue by joel2106** [sparkfun/Logic_Level_Bidirectional#3]
Hello,
I'm trying to send data to WS2812 LEDs.

I connect 3.3V from Teensy µC to LV and separate 5V to HV an the LEDs. They're both on the same ground. Now I connect the data pin of the Teensy to LV1 and HV1 to the data pin of the LEDs.

When I look at the levels on the data pins on LV and HV side they're both on 3.3V. HV side slightly lower.

What am I doing wrong?

**Comment by santaimpersonator** [comment]
Hi there, it sounds like you are looking for [technical assistance](https://www.sparkfun.com/technical_assistance). Unfortunately, this is channel for issues specifically with the hardware. Please feel free to post a topic in our [forums](https://forum.sparkfun.com/). Our technical support team will do their best to assist you.

**Comment by GitBruno** [comment]
It might be a hardware issue as the pins are called HV and LV but if you want to go from 3.3 to 5V we will need to connect the 5V to LV and 3.3V to HV. So these are directional. Meaning ports should be called `PI` and `PO` (Power in / Power Out) 

And Logic In/Out:

    LI1, LI2, LI3, LI4, LO1, LO2, LO3, LO4

**Comment by santaimpersonator** [comment]
@GitBruno I think you meant "5V to HV and 3.3V to LV". As this device is bi-directional, that naming convention (PI, PO, LI, LO) would cause users to accidentally hookup the device backwards. The "higher" voltage needs to be connected to the pull-up resistor and the "lower" voltage needs to be connected to the transistor for the circuit to work properly.

Please refer to the hookup guide for this product:
https://learn.sparkfun.com/tutorials/bi-directional-logic-level-converter-hookup-guide

**Comment by GitBruno** [comment]
Nope. I needed to connect the PCB in reverse to make it work! Otherwise I have the same problem as OP #3

**Comment by santaimpersonator** [comment]
@GitBruno As mentioned in the [hookup guide](https://learn.sparkfun.com/tutorials/bi-directional-logic-level-converter-hookup-guide), the circuit (and silk) on the board is based upon this application note: [Philips Application Note AN97055](http://cdn.sparkfun.com/tutorialimages/BD-LogicLevelConverter/an97055.pdf).

*\*As a note, I noticed you mentioned "power out"... there isn't a voltage regulation/conversion for a power out on the board. Users should be supplying both the "lower" (LV) and "higher" voltage (HV) to the board.*

**Comment by GitBruno** [comment]
Thanks for the guide! All I can say is that I needed to switch sides to drive a 5v SPI using a 3.3v MC using this layout.

**Comment by PipeDeveloper** [comment]
For a directional signal you should use just one transistor 2n2222 or 2n3904, your data 3.3v goes to base, 5v to collector and the emitter to your device you want to hook 5v digital signal.

This module is bidirectional mosfet, so HV is 5v and Lv is 3.3v. This circuit is designed to pull 3.3v to 5v signals and pull down 5v to 3.3v signals (thats why its called bi-directional).

I use also WS2812B RGB Leds without a problem with ESP8266, works like a charm, just one channel is needed.
I leave you a simple schematic that anyone could understand
![Sin título](https://user-images.githubusercontent.com/35433329/119174784-041e6300-ba37-11eb-84d1-50be8f1cdcac.png)
